
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SagaDB.Mob;
using SagaDB.Actor;
using SagaMap.Skill.Additions.Global;
using SagaMap.Manager;
using SagaDB.Map;

namespace SagaMap.Skill.SkillDefinations.Sage
{
    /// <summary>
    /// 活化杖（リビングスタッフ）
    /// </summary>
    public class StaffCtrl : ISkill
    {
        #region ISkill Members
        public int TryCast(ActorPC sActor, Actor dActor, SkillArg args)
        {
            Map map = MapManager.Instance.GetMap(sActor.MapID);

            if (map.Info.Flag.Test(MapFlags.Healing))
            {
                return -6;
            }
            return 0;
        }
        public void Proc(Actor sActor, Actor dActor, SkillArg args, byte level)
        {

            int lifetime = 20000 * level;
            Map map = Manager.MapManager.Instance.GetMap(sActor.MapID);
            ActorMob mob = map.SpawnMob(26330000, SagaLib.Global.PosX8to16(args.x, map.Width)
                                               , SagaLib.Global.PosY8to16(args.y, map.Height)
                                               , 2500, sActor);

            //mob.type = ActorType.ANOTHERMOB;
            mob.Owner = sActor;
            ActorEventHandlers.MobEventHandler eE = (ActorEventHandlers.MobEventHandler)mob.e;
            mob.Buff.CannotMove = true;
            eE.AI.Master = sActor;
            //修复
            eE.AI.Mode = new Mob.AIMode(1);
            eE.AI.Mode.EventAttacking.Add(3281, 100);	//魔法衝擊波
            eE.AI.Mode.EventAttackingSkillRate = 100;

            // 隱身技能處理邏輯
            List<ActorMob> actorsInRange = new List<ActorMob>();
            foreach (Actor Mapactor in Manager.MapManager.Instance.GetMap(mob.MapID).Actors.Values)
            {
                if (Mapactor != null && Mapactor.type == ActorType.MOB)
                {
                    List<MobType> typesToIgnore = new List<MobType>
        {
            // 添加其他要忽略的怪物類型
        MobType.HUMAN_BOSS,MobType.HUMAN_BOSS_SKILL,MobType.HUMAN_BOSS_CHAMP,MobType.HUMAN_SKILL_BOSS_CHAMP,MobType.HUMAN_SMARK_BOSS_HETERODOXY,
        MobType.HUMAN_BOSS_MIRROR,MobType.HUMAN_BOSS_SKILL_CHAMP,MobType.PLANT_BOSS,MobType.PLANT_BOSS_SKILL,MobType.PLANT_BOSS_SKILL_NOTPTDROPRANGE,MobType.PLANT_MATERIAL_BOSS_MARK,
        MobType.PLANT_MATERIAL_EAST_BOSS_SKILL_WALL,MobType.PLANT_MATERIAL_WEST_BOSS_SKILL_WALL,MobType.PLANT_MATERIAL_SOUTH_BOSS_SKILL_WALL,MobType.PLANT_MATERIAL_NORTH_BOSS_SKILL_WALL,MobType.ROCK_BOSS_SKILL_WALL,
        MobType.ROCK_MATERIAL_BOSS_NOTPTDROPRANGE, MobType.ROCK_MATERIAL_BOSS_SKILL_NOTPTDROPRANGE,MobType.ROCK_BOSS_SKILL_NOTPTDROPRANGE, MobType.ROCK_MATERIAL_BOSS,MobType.BIRD_BOSS,MobType.BIRD_BOSS_SKILL,
        MobType.BIRD_SPBOSS_SKILL,MobType.ANIMAL_BOSS,MobType.ANIMAL_BOSS_SKILL,MobType.ANIMAL_SPBOSS_SKILL,MobType.ANIMAL_BOSS_SKILL_NOTPTDROPRANGE,
        MobType.ANIMAL_SPBOSS_SKILL_NOTPTDROPRANGE,MobType.ANIMAL_BOSS_NOTPTDROPRANGE,MobType.WATER_ANIMAL_BOSS,MobType.WATER_ANIMAL_BOSS_SKILL,MobType.INSECT_BOSS,MobType.INSECT_BOSS_SKILL,
        MobType.INSECT_BOSS_NOTPTDROPRANGE,MobType.INSECT_BOSS_CHAMP,MobType.MAGIC_CREATURE_BOSS,MobType.MAGIC_CREATURE_BOSS_SKILL,MobType.MAGIC_CREATURE_BOSS_SKILL_NOTPTDROPRANGE,MobType.UNDEAD_BOSS,MobType.UNDEAD_BOSS_SKILL,MobType.UNDEAD_BOSS_BOMB_SKILL,
        MobType.UNDEAD_BOSS_SKILL_CHAMP,MobType.UNDEAD_BOSS_CHAMP_BOMB_SKILL_NOTPTDROPRANGE,MobType.UNDEAD_BOSS_SKILL_NOTPTDROPRANGE,MobType.MACHINE_BOSS,MobType.MACHINE_BOSS_SKILL,
        MobType.MACHINE_BOSS_CHAMP,MobType.MACHINE_SKILL_BOSS,MobType.MACHINE_SMARK_BOSS_SKILL_HETERODOXY_NONBLAST,MobType.MACHINE_BOSS_SKILL_NOTPTDROPRANGE,MobType.ELEMENT_BOSS_SKILL,MobType.ELEMENT_SKILL_BOSS,MobType.EVENT_BOSS,MobType.PLANT_BOSS_BSEARCH,
        MobType.PLANT_BOMB_BOSS_SKILL,MobType.PLANT_INFO_NOTPTDROPRANGE,MobType.ANIMAL_BOSS_BSEARCH_SKILL,MobType.INSECT_BOSS_BSEARCH, MobType.INSECT_BOMB_BOSS_SKILL,
        MobType.ANIMAL_BOMB_BOSS_SKILL,MobType.HUMAN_BOSS_NOTPTDROPRANGE,MobType.HUMAN_BOSS_BSEARCH_SKILL_NOTPTDROPRANGE,MobType.HUMAN_BOSS_SKILL_NOTPTDROPRANGE, MobType.MACHINE_BOSS_BSEARCH_SKILL,
        MobType.PLANT_BOSS_BSEARCH_SKILL,MobType.PLANT_BOSS_NOTOUCH,MobType.MACHINE_SKILL_BOSS_BSEARCH,MobType.MAGIC_CREATURE_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE,MobType.MAGIC_CREATURE_BOSS_SKILL_INFO_NOTPTDROPRANGE,
        MobType.MACHINE_BOSS_BSEARCH_CHAMP,MobType.ANIMAL_SPBOSS_BSEARCH_SKILL_NOTPTDROPRANGE,MobType.ROCK_BOSS_BSEARCH_SKILL_NOTPTDROPRANGE, MobType.WATER_ANIMAL_BOSS_BSEARCH_SKILL_NOTPTDROPRANGE,
        MobType.WATER_ANIMAL_BOSS_BSEARCH_SKILL,MobType.MACHINE_BOSS_BSEARCH_,MobType. MACHINE_SKILL_BOSS_BSEARCH_LVDIFF_NONBLAST_ATRE_,MobType. HUMAN_BOSS_BSEARCH_CHAMP,MobType. UNDEAD_BOSS_BSEARCH_CHAMP_BOMB_SKILL_NOTPTDROPRANGE,MobType. UNDEAD_BOSS_BSEARCH_BOMB_SKILL,MobType.HUMAN_BOSS_BSEARCH,MobType.HUMAN_SKILL_BOSS_BSEARCH_CHAMP,MobType.ANIMAL_BOSS_BSEARCH_SKILL_NOTPTDROPRANGE,MobType.UNDEAD_BOSS_BSEARCH_SKILL,
        MobType.MACHINE_BOSS_BSEARCH_SKILL_CHAMP,MobType. MACHINE_BOSS_BSEARCH_SKILL_NOTPTDROPRANGE,MobType. MACHINE_BOSS_BSEARCH,MobType.WATER_ANIMAL_BOSS_BSEARCH,MobType. HUMAN_BOSS_BSEARCH_SKILL_CHAMP,MobType. MAGIC_CREATURE_BOSS_BSEARCH_INFO_NOTPTDROPRANGE,
        MobType. PLANT_BOSS_BSEARCH_INFO_NOTPTDROPRANGE,MobType. ANIMAL_BOSS_BSEARCH_INFO_NOTPTDROPRANGE,MobType.BIRD_NOTPTDROPRANGE,MobType.MAGIC_CREATURE_SPBOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE,MobType.MAGIC_CREATURE_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_LVDIFF_PTRE,
        MobType.MAGIC_CREATURE_BOSS_SKILL_INFO_NOTPTDROPRANGE_BSEARCH_PTRE,MobType.HUMAN_BOSS_BSEARCH_SKILL,MobType.UNDEAD_BOSS_BSEARCH_SKILL_CHAMP,
        MobType.HUMAN_BOSS_BSEARCH_MIRROR,MobType.WATER_ANIMAL_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE,MobType.WATER_ANIMAL_BOSS_SKILL_INFO_NOTPTDROPRANGE,MobType.BIRD_BOSS_BSEARCH,MobType.BIRD_SPBOSS_BSEARCH_SKILL,
        MobType.BIRD_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE,MobType.BIRD_BOSS_SKILL_INFO_NOTPTDROPRANGE,MobType.ELEMENT_BOSS_BSEARCH_SKILL,MobType.ELEMENT_BOSS_BSEARCH_SKILL_NOTPTDROPRANGE,MobType.ELEMENT_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE,
        MobType.ELEMENT_BOSS_SKILL_INFO_NOTPTDROPRANGE,MobType.ELEMENT_BOSS_NOTOUCH,MobType.ELEMENT_BOSS,MobType.HUMAN_INFO_BOSS_BSEARCH_NOTPTDROPRANGE,
        MobType.HUMAN_INFO_BOSS_BSEARCH_SKILL_NOTPTDROPRANGE,MobType.TREASURE_BOX_MATERIAL_BOSS_SKILL,MobType. KNIGHTS_WAR_BOSS_MATERIAL,MobType.HUMAN_INFO_BOSS_NOTPTDROPRANGE,MobType.ROCK_INFO_MATERIAL_NOTPTDROPRANGE,
        MobType.PLANT_MATERIAL_BOSS,MobType.ROCK_BOSS,MobType.TREE_BOSS_MATERIAL,MobType.MAGIC_CREATURE_MATERIAL_BOSS_NONBLAST,MobType.PLANT_MATERIAL_NOTOUCH_BOSS_SKILL_WALL,
        MobType.WATER_ANIMAL_BOSS_SKILL_NOTPTDROPRANGE,MobType.MACHINE_BOSS_SKILL_CHAMP,MobType.MAGIC_CREATURE_BOSS_INFO_NOTPTDROPRANGE,MobType.PLANT_BOSS_INFO_NOTPTDROPRANGE,MobType.ANIMAL_BOSS_INFO_NOTPTDROPRANGE,
        MobType.ELEMENT_BOSS_SKILL_NOTPTDROPRANGE,MobType.HUMAN_INFO_BOSS_SKILL_NOTPTDROPRANGE,MobType.KING_BOSS,
        MobType.ANIMAL_BOSS_SKILL_CHAMP,MobType.ROCK_MATERIAL_BOSS_NOTPTDROPRANGE_CHAMP,MobType.PLANT_NOTPTDROPRANGE_BOSS,MobType.ANIMAL_BOSS_SKILL_NODEATH_NONBLAST_NOHIDING_NOSKETCH_NORTH,
        MobType.INSECT_LVDIFF,MobType.INSECT_BOSS_SKILL_NODEATH_NONBLAST_NOHIDING_NOSKETCH_NORTH,MobType.INSECT_NOTPTDROPRANGE_BOSS,
        MobType.WATER_ANIMAL_NOTPTDROPRANGE_BOSS,MobType.ANIMAL_BOSS_BSEARCH_NONBLAST_SKILL,MobType.ANIMAL_BOSS_NONBLAST_SKILL,
        MobType.INSECT_BOSS_BSEARCH_NONBLAST,MobType.MAGIC_CREATURE_NOTPTDROPRANGE_BOSS,MobType.UNDEAD_NOTPTDROPRANGE_BOSS,MobType.UNDEAD_BOSS_NONBLAST_SKILL,MobType.MAGIC_CREATURE_BOSS_LVDIFF,
        MobType.MAGIC_CREATURE_NOTPTDROPRANGE_BOSS_SKILL,MobType.MAGIC_CREATURE_BOSS_SKILL_NODEATH_NONBLAST_NOHIDING_NOSKETCH_NORTH,MobType.MAGIC_CREATURE_BOSS_SKILL_LVDIFF_INFO_NOTPTDROPRANGE_PTRE_FAKE,MobType.MAGIC_CREATURE_BOSS_LVDIFF_FAKE,
        MobType.MAGIC_CREATURE_SKILL_BOSS_LVDIFF_FAKE,MobType.HUMAN_BOSS_NODEATH_NONBLAST_NORTH_WEST,MobType.ANIMAL_BOSS_BSEARCH_NONBLAST,MobType.BIRD_BOSS_SKILL_NODEATH_NONBLAST_NOHIDING_NOSKETCH_NORTH,
        MobType.MACHINE_BOSS_SKILL_NODEATH_NONBLAST_NOHIDING_NOSKETCH_NORTH,MobType.MACHINE_BOSS_SKILL_NODEATH_NONBLAST_NOHIDING_NOSKETCH,MobType.PLANT_BOSS_SKILL_NODEATH_NONBLAST_NOHIDING_NOSKETCH_NORTH,MobType.HUMAN_BOSS_BSEARCH_NONBLAST,
        MobType.NONE_MATERIAL_LVDIFF_BOSS,MobType.MACHINE_BOSS_NONBLAST_SKILL_SOUTH,MobType.MACHINE_BOSS_LVDIFF,MobType.ANIMAL_BOSS_BSEARCH_SKILL_LVDIFF,MobType.MACHINE_SKILL_BOSS_BSEARCH_NOHIDING,
        MobType.MACHINE_BOSS_BSEARCH_NOHIDING,MobType.MACHINE_SKILL_BOSS_BSEARCH_NOHIDING_CHAMP,MobType.ANIMAL_BOSS_BSEARCH_SKILL_LVDIFF_NONBLAST_SOUTH_NOSKETCH,MobType.ANIMAL_NODEATH_LVDIFF_NOSKETCH,
        MobType.ANIMAL_NODEATH_SKILL_LVDIFF_NOSKETCH,MobType.ANIMAL_BOSS_NODEATH_SKILL_LVDIFF_NOSKETCH,MobType.INSECT_BOSS_LVDIFF,MobType.WATER_ANIMAL_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_REC,
        MobType.WATER_ANIMAL_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE,MobType.WATER_ANIMAL_BOSS_NODEATH_NONBLAST,MobType.HUMAN_SKILL_BOSS_BSEARCH,MobType.HUMAN_BOSS_BSEARCH_LVDIFF,MobType.ELEMENT_BOSS_NODEATH_NONBLAST_SOUTH,MobType.ELEMENT_NOTPTDROPRANGE_BOSS,MobType.ELEMENT_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_REC,
        MobType. ELEMENT_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE,MobType.ELEMENT_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_NOHIDING,MobType.PLANT_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_REC,
        MobType.PLANT_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE,MobType. PLANT_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_NOHIDING,MobType.PLANT_BOSS_NODEATH_NONBLAST,MobType.ANIMAL_BOSS_NODEATH_NONBLAST,
        MobType.ROCK_BOSS_SKILL,MobType.MACHINE_BOSS_SKILL_LVDIFF,MobType.MACHINE_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_REC,MobType.MACHINE_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE,MobType.MACHINE_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_NOHIDING,MobType.MAGIC_CREATURE_BOSS_BSEARCH_NONBLAST,
        MobType.MAGIC_CREATURE_BOSS_BSEARCH_SKILL_NONBLAST,MobType.MAGIC_CREATURE_BOSS_NODEATH_NONBLAST,MobType.MACHINE_SKILL_NODEATH_BOSS_BSEARCH,MobType.MACHINE_BOSS_NODEATH_NONBLAST,MobType.MACHINE_NODEATH_BOSS_BSEARCH,
        MobType.MACHINE_BOSS_BSEARCH_NOTOUCH,MobType. MACHINE_BOSS_BSEARCH_NONBLAST_SKILL,MobType.MACHINE_BOSS_SKILL_NOTPTDROPRANGE_NODEATH_NONBLAST,MobType.MAGIC_CREATURE_BOSS_BSEARCH_NONBLAST_SKILL,MobType.ANIMAL_BOMB_NONBLAST_NOTPTDROPRANGE_BOSS,MobType.ANIMAL_BOSS_NONBLAST_SKILL_SOUTH,
        MobType.ANIMAL_BOSS_NONBLAST,MobType.EGG_BOSS_SKILL_NOTPTDROPRANGE,MobType.ANIMAL_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_REC,MobType.ANIMAL_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE,MobType.ANIMAL_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_NOHIDING,MobType.INSECT_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_REC,
        MobType. INSECT_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE,MobType.INSECT_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_NOHIDING,MobType.WATER_ANIMAL_BOSS_BSEARCH_SKILL_REC_NOTPTDROPRANGE,MobType.WATER_ANIMAL_BOSS_BSEARCH_SKILL_REC,MobType.UNDEAD_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_REC,
        MobType.UNDEAD_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE,MobType.UNDEAD_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_NOHIDING,MobType.INSECT_SKILL_BOSS_SKILL,MobType.ANIMAL_BOSS_BSEARCH_SKILL_REC_NOTPTDROPRANGE_NOHIDING_NONBLAST,
        MobType.ELEMENT_SKILL_BOSS_SKILL,MobType.NONE_BOSS_PLAYER,MobType.HUMAN_BOSS_BSEARCH_NONBLAST_EAST,MobType.HUMAN_BOSS_SKILL_LVDIFF_NONBLAST_NOHIDING_WEST_NOSKETCH,MobType.HUMAN_BOSS_BSEARCH_SKILL_NONBLAST_NOSKETCH,MobType.HUMAN_BOSS_BSEARCH_SKILL_NONBLAST_SOUTH,
        MobType.HUMAN_BOSS_BSEARCH_NONBLAST_SKILL,MobType.MAGIC_CREATURE_SPBOSS_SKILL_INFO_NOTPTDROPRANGE_BSEARCH_PTRE,MobType.ELEMENT_BOSS_SKILL_INFO_NOTPTDROPRANGE_BSEARCH_PTRE,MobType.ELEMENT_BOSS_BOSS_SKILL_NODEATH_NONBLAST_NOHIDING_NOSKETCH_NORTH,MobType.ROCK_BOSS_SKILL_NOHIDING_BOSS_BSEARCH_NONBLAST,
        MobType.ROCK_BOSS_SKILL_NOHIDING_BOSS_NONBLAST,MobType.ROCK_BOSS_SKILL_INFO_NOTPTDROPRANGE_BSEARCH_PTRE_NOHIDING,MobType.ROCK_BOSS_BSEARCH_NONBLAST,MobType.MAGIC_CREATURE_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_REC,MobType.MAGIC_CREATURE_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE,
        MobType.UNDEAD_BOSS_BSEARCH_NONBLAST_NOHIDING_CHAMP,MobType.UNDEAD_NOTPTDROPRANGE_BOSS_SKILL,MobType.HUMAN_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_REC,MobType.HUMAN_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE,MobType.BIRD_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_REC,
        MobType.BIRD_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE,MobType.ROCK_CHRONICLE,MobType.ROCK_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE_REC,MobType.ROCK_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE_PTRE,MobType.ROCK_MATERIAL_SMARK,
        MobType.NONE_BOSS_NOHIDING,MobType.ELEMENT_BOSS_BSEARCH_CHAMP,MobType.HUMAN_SPBOSS_BSEARCH_SKILL_NOTPTDROPRANGE_PTRE,MobType.INSECT_BOSS_BSEARCH_SKILL_NOTPTDROPRANGE_PTRE,MobType.INSECT_NOHIDING_BOSS_BSEARCH_SKILL_SOUTH_VISIONMAX_SMARK,
        MobType.ANIMAL_BOSS_NOHIDING,MobType.ANIMAL_NOTPTDROPRANGE_BOSS,MobType.ANIMAL_BOSS_BSEARCH_SKILL_REC_NOTPTDROPRANGE_NOHIDING_NONBLAST_INFO,MobType.MACHINE_BOSS_BSEARCH_NONBLAST,
        MobType.MACHINE_BOSS_NONBLAST,MobType.BIRD_BOSS_BSEARCH_SKILL_REC_NOTPTDROPRANGE_NONBLAST,MobType.BIRD_BSEARCH_SKILL_NOTPTDROPRANGE_NOHIDING,MobType.BIRD_BOSS_NONBLAST_SKILL_SOUTH,MobType.BIRD_BOSS_SKILL_INFO_NOTPTDROPRANGE_PTRE_NOHIDING,
        MobType.HUMAN_BOSS_SKILL_INFO_NOTPTDROPRANGE_PTRE_NOHIDING,MobType.HUMAN_BOSS_SKILL_INFO_NOTPTDROPRANGE_PTRE,MobType.WATER_ANIMAL_BOSS_SKILL_INFO_NOTPTDROPRANGE_PTRE_NOHIDING,MobType.MACHINE_SKILL_BOSS_BSEARCH_NONBLAST_PLAYER,MobType.WATER_ANIMAL_BOSS_BSEARCH_SKILL_NOTPTDROPRANGE_PLAYER,
        MobType.WATER_ANIMAL_BOSS_BSEARCH_NONBLAST,MobType.ANIMAL_BOSS_BSEARCH_NONBLAST_PLAYER_REC,MobType.WATER_ANIMAL_NOHIDING_BOSS_BSEARCH_SKILL_WEST_VISIONMAX_MOVENOTCELL_SMARK,MobType.WATER_ANIMAL_NOHIDING_BOSS_BSEARCH_SKILL_MOVENOTCELL_SMARK,MobType.HUMAN_BOSS_NOTPTDROPRANGE_BSEARCH,
        MobType.HUMAN_BOSS_SKILL_NOTOUCH,MobType.HUMAN_BOSS_NOTPTDROPRANGE_NOHIDING_SKILL_BSEARCH,MobType.HUMAN_BOSS_NOTPTDROPRANGE_BSEARCH_SKILL,MobType.HUMAN_BOSS_NOTPTDROPRANGE_SKILL_BSEARCH,MobType.HUMAN_BOSS_NOTPTDROPRANGE_SKILL_CHAMP_BSEARCH,
        MobType.HUMAN_SKILL_BOSS_NOHIDING_NONBLAST_COMBATNPCNOTOUCH_PARTNERNOTOUCH,MobType.HUMAN_BOSS_BSEARCH_NONBLAST_NOSKETCH_SKILL_MIRROR,MobType.HUMAN_BOSS_SOUTH_LVDIFF_NONBLAST_BSEARCH_NODEATH_NOHIDING_NOSKETCH,MobType.HUMAN_BOSS_SKILL_WEST_LVDIFF_NONBLAST_BSEARCH_NODEATH_NOHIDING_NOSKETCH,MobType.ELEMENT_BOSS_NONBLAST_NOSKETCH,
        MobType.ELEMENT_BOSS_SKILL_NODEATH_NONBLAST_NOHIDING_NOSKETCH_NORTH,MobType.ELEMENT_BOSS_NOHIDING_NONBLAST_NOSKETCH_NORTH_NODIR_NOCAMCHK_SMARK,MobType.ELEMENT_BOSS_NONBLAST_NOHIDING_NOSKETCH_NOCAMCHK,MobType.HUMAN_NODEATH_LVDIFF,MobType.HUMAN_BOSS_NODEATH_NONBLAST_SKILL,
        MobType.MAGIC_CREATURE_BOSS_NONBLAST_REC,MobType.MAGIC_CREATURE_BOSS_NONBLAST,MobType.ELEMENT_SKILL_NODEATH,MobType.ELEMENT_SKILL_BOSS_BSEARCH_NONBLAST,MobType.ELEMENT_NOHIDING_BOSS_BSEARCH_SKILL_MOVENOTCELL_SMARK_NOTOUCH,
        MobType.MAGIC_CREATURE_BOSS_BSEARCH_SKILL_REC_NOTPTDROPRANGE_NOHIDING_NONBLAST_INFO,MobType.ELEMENT_NODEATH_NOHIDING,MobType.ELEMENT_LVDIFF_NODEATH,MobType.ELEMENT_CHRONICLE,MobType.MAGIC_CREATURE_BOSS_SKILL_LVDIFF,MobType.MAGIC_CREATURE_BOSS_SKILL_NOTPTDROPRANGE_NODEATH_LVDIFF,
        MobType.BIRD_NOTPTDROPRANGE_BOSS,MobType.ELEMENT_LVDIFF,MobType.WATER_ANIMAL_BOSS_NOTPTDROPRANGE,MobType.WATER_ANIMAL_BOSS_SKILL_NODEATH_NONBLAST_NOHIDING_NOSKETCH_NORTH,MobType.MAGIC_CREATURE_BOSS_MARK_SKILL,MobType.ROCK_MATERIAL_NOTPTDROPRANGE,
        MobType.ROCK_MATERIAL_COMBATNPCNOTOUCH_PARTNERNOTOUCH_BOSS_NODEATH_NOSKETCH,MobType.PLANT_MATERIAL_BOSS_LVDIFF,MobType.MACHINE_BOSS_SKILL_NODEATH_NONBLAST,MobType.MAGIC_CREATURE_NOSKILLEFFECT_COMBATNPCNOTOUCH_BOSS_NONBLAST,
        MobType.NONE_MATERIAL_SOUTH_BOSS_SKILL_WALL,MobType.NONE_MATERIAL_SOUTH_WEST_BOSS_SKILL_WALL,MobType.NONE_MATERIAL_WEST_BOSS_SKILL_WALL,MobType.NONE_MATERIAL_NORTH_WEST_BOSS_SKILL_WALL,MobType.NONE_MATERIAL_NORTH_BOSS_SKILL_WALL,MobType.NONE_MATERIAL_NORTH_EAST_BOSS_SKILL_WALL,MobType.NONE_MATERIAL_EAST_BOSS_SKILL_WALL,
        MobType.NONE_MATERIAL_SOUTH_EAST_BOSS_SKILL_WALL,MobType.MAGIC_CREATURE_MATERIAL_BOSS_NONBLAST_COMBATNPCNOTOUCH,MobType.PLANT_MATERIAL_EAST_NOTOUCH_BOSS_SKILL_WALL_MOVENOTCELL,MobType.PLANT_MATERIAL_SOUTH_NOTOUCH_BOSS_SKILL_WALL_MOVENOTCELL,MobType.PLANT_MATERIAL_NOTOUCH_BOSS_SKILL_WALL_MOVENOTCELL,
        MobType.NONE_MATERIAL_SOUTH_BOSS_SKILL_WALL_NOTOUCH,MobType.NONE_MATERIAL_SOUTH_WEST_BOSS_SKILL_WALL_NOTOUCH,MobType.NONE_MATERIAL_WEST_BOSS_SKILL_WALL_NOTOUCH,MobType.NONE_MATERIAL_NORTH_WEST_BOSS_SKILL_WALL_NOTOUCH,MobType.NONE_MATERIAL_NORTH_BOSS_SKILL_WALL_NOTOUCH,MobType.NONE_MATERIAL_NORTH_EAST_BOSS_SKILL_WALL_NOTOUCH,
        MobType.NONE_MATERIAL_EAST_BOSS_SKILL_WALL_NOTOUCH,MobType.NONE_MATERIAL_SOUTH_EAST_BOSS_SKILL_WALL_NOTOUCH,MobType.ROCK_BOSS_NONBLAST_SKILL,MobType.PLANT_MATERIAL_BOSS_SKILL_WALL,MobType.NONE_BOSS_MATERIAL_NOTOUCH_NONBLAST_SKILL,MobType.NONE_BOSS_MATERIAL_NOTOUCH_NONBLAST_SKILL_MOVENOTCELL,
        MobType.NONE_BOSS_NONBLAST_SKILL,MobType.NONE_BOSS_MATERIAL_NOTOUCH_NONBLAST_SKILL_NOHIDING_VISIONMAX_NOINFO,MobType.NONE_BOSS_MATERIAL_NOTOUCH_NOHIDING_NONBLAST_NOINFO,
        MobType.HUMAN_BOSS_NONBLAST,MobType.MAGIC_CREATURE_BOSS_NONBLAST_SKILL,MobType.UNDEAD_BOSS_NONBLAST,MobType.NONE_BOSS_MATERIAL_NOTOUCH_NONBLAST_SKILL_MOVENOTCELL_NOHIDING_VISIONMAX_NOINFO,MobType.NONE_BOSS_MATERIAL_SOUTH_NOTOUCH_NONBLAST_SKILL_NOHIDING_VISIONMAX_NOINFO,
        MobType.NONE_BOSS_MATERIAL_SOUTH_NOTOUCH_NONBLAST_SKILL_MOVENOTCELL_NOHIDING_VISIONMAX_NOINFO,MobType.NONE_BOSS_NONBLAST_SKILL_NOHIDING_NOSKETCH,MobType.NONE_BOSS_NONBLAST_SKILL_NOHIDING_NOSKETCH_PARTNERNOTOUCH,MobType.ROCK_BOSS_NONBLAST_SKILL_NOHIDING_NOSKETCH_PARTNERNOTOUCH,MobType.NONE_BOSS_MATERIAL_NOTOUCH_NONBLAST_SKILL_NOHIDING_NOHPVIEW_NOINFO,
        MobType.ROCK_BOSS_NONBLAST_SKILL_NOSKETCH,MobType.MAGIC_CREATURE_BOSS_NOSKETCH,MobType.HUMAN_BOSS_NOSKETCH,MobType.ANIMAL_NOHIDING_NODEATH_NOSKETCH,MobType.NONE_BOSS_MATERIAL_NONBLAST_SKILL_MOVENOTCELL_NOHIDING_VISIONMAX_NOSKETCH_NOERASETIME_DAMAGE1,
        MobType.ELEMENT_BOSS_NOTOUCH_NONBLAST_NOSKETCH_NOCAMCHK,MobType.ELEMENT_BOSS_NONBLAST_NOHIDING_NOSKETCH_NOCAMCHK_SKILL_LVDIFF,MobType.ELEMENT_BOSS_NONBLAST_NOSKETCH_NODEATH_NONBLAST_SKILL,
        MobType.NONE_BOSS_NODEATH_NONBLAST_NOHPVIEW,MobType.NONE_BOSS_NODEATH_NONBLAST_VISIONMAX_NOHPVIEW,MobType.MACHINE_SKILL_BOSS_SKILL,MobType.ANIMAL_BOSS_BSEARCH_NOTPTDROPRANGE,MobType.ANIMAL_BOMB_BOSS_BSEARCH_SKILL,MobType.ANIMAL_BOSS_BSEARCH,MobType.ANIMAL_BOSS_BSEARCH_SKILL_INFO_NOTPTDROPRANGE,
        MobType.ANIMAL_BOSS_SKILL_INFO_NOTPTDROPRANGE,MobType.BIRD_BOSS_SKILL_NOTPTDROPRANGE,MobType.BIRD_BOSS_BSEARCH_SKILL,MobType.INSECT_BOSS_BSEARCH_SKILL,MobType.MAGIC_CREATURE_BOSS_SKIL,MobType.UNDEAD_BOSS_BSEARCH,
        MobType.UNDEAD_BOSS_BSEARCH_SKILL_NOTPTDROPRANGE,MobType.UNDEAD_BOSS_NOTPTDROPRANGE,MobType.MAGIC_CREATURE_BOSS_BSEARCH,MobType.MAGIC_CREATURE_BOSS_BSEARCH_SKILL,MobType.MAGIC_CREATURE_BOSS_BSEARCH_SKILL_NOTPTDROPRANGE,
        };
                    if (!typesToIgnore.Contains(mob.BaseData.mobType))
                    {
                    }
                    else
                    {
                        actorsInRange.Add((ActorMob)Mapactor);
                    }
                }
            }
            foreach (ActorMob actorInRange in actorsInRange)
            {
                if (actorInRange != null && ((ActorEventHandlers.MobEventHandler)actorInRange.e).AI.Hate.ContainsKey(mob.ActorID))
                {
                    ((ActorEventHandlers.MobEventHandler)actorInRange.e).AI.Hate.TryRemove(mob.ActorID, out _);//二哈更改Hate
                }
            }

            StaffCtrlBuff skill = new StaffCtrlBuff(mob, args.skill, sActor, lifetime);
            SkillHandler.ApplyAddition(sActor, skill);
        }
        public class StaffCtrlBuff : DefaultBuff
        {
            private ActorMob mob;
            public StaffCtrlBuff(ActorMob mob, SagaDB.Skill.Skill skill, Actor actor, int lifetime)
                : base(skill, actor, "StaffCtrl", lifetime)
            {
                this.OnAdditionStart += this.StartEvent;
                this.OnAdditionEnd += this.EndEvent;
                this.mob = mob;
            }

            void StartEvent(Actor actor, DefaultBuff skill)
            {

            }

            void EndEvent(Actor actor, DefaultBuff skill)
            {
                Map map = Manager.MapManager.Instance.GetMap(actor.MapID);
                if (mob != null)
                {
                    mob.ClearTaskAddition();
                    map.DeleteActor(mob);
                }
            }
        }
        #endregion
    }
}


